(function(){

  var homos = [
    //--------------parody-----------------
    //"(One-Punch Man)", //tatsumaki is cute. Why you choose this, fujosi!
"(Haikyuu!!)",
"(Shingeki no Kyojin)",  //Mikasa is not cute anyway
"(Kuroko no Basuke)", 
"(Katekyoo Hitman REBORN!)",
"(Touken Ranbu)",
"(Yowamushi Pedal)",
"(Uta no Prince-sama)",
"(Hoozuki no Reitetsu)",
"(Kekkai Sensen)",
"(Free!)",
"(ALDNOAH.ZERO)",
"(Ensemble Stars!)",
"(Sengoku Basara)",
"(Bakumatsu Rock)",
"(DRAMAtical Murder)",
"(Ao no Exorcist)",
"(Daiya no Ace)",
"(Gintama)",
"(Katekyo Hitman REBORN!)",
"リヴァイ兵長",  //I hate this short guy!!
"少年×ケモノ",   
"ケモホモ",
"(Teenage Mutant Ninja Turtles)",
"(Buraiden Gai)",
"(Prince of Tennis)",
"(TIGER & BUNNY)",
"(Osomatsu-san)",
"(GANGSTA.)",
"(Toriko)",
"(Durarara!!)",
"(Inazuma Eleven)",
"(Summer Wars)", //why on earth they choose!!
"(Tokyo Ghoul)", 
"(Kaiji)", //OMG
"(Dramatical Murder)",
"(Natsume's Book of Friends",
"(natsume yuujin",
"(sweet pool",
"(Sekaiichi Hatsukoi)",
"(LOVELESS",
//------------author---------------
"[001 (Iimo)",
"[10.10MHz (Totofumi)",
"[100Mjack (Ebisawa Nira)",
"[238 (Hachi, Mitsu)",
"[23924 (Miko)",
"[39dmp (tachibanaei)",
"[3×3CROSS (Marimo)",
"[4DIP (Tarte)",
"[500ft (Sorao)",
"[6109 (Kirishiki Tokico)",
"[6counter (Shuukichi)",
"[84 (Hashi)",
"[8days (Kuon Marino)",
"[8°]",
"[:DOG VILLE, Tokyo Coin Rocker Baby",
"[@N (unico)",
"[A-mw. (makka)",
"[Abara ga Itai (Shindai)",
"[Acchicchi (Kanegae Shouko)",
"[ADVANX (ADVANX)",
"[Afuroyaen (Nyankichi)",
"[Aisukureyo (Hoshikuzu Noyu)",
"[Akagirenya (Konokoyun, Akaboshi)",
"[Akareshina (Hidaka Naruse)",
"[Ake no Myoujou (Yuuki Takeru)",
"[Akitaku Kikaku (Taku Hiraku)",
"[Akiya (Suzusawa Aki)",
"[Akuochisukii Kyoushitsu (Akuochisukii Sensei)",
"[Al:side-G (Hisui Yu)",
"[Altopia (Alto)",
"[Amarans (Fujimura Marina)",
"[Ambient (Kuriyama Natsuki)",
"[ame-kan (K.Hinagi)",
"[Ameagari After School (Kimoto Hajime)",
"[American ☆ Rock (Kotarou)",
"[Amiya (Nono)",
"[Animalism (Takagi Kyou)",
"[anything (naop)",
"[Aozora (Nosada)",
"[Apoepo Company. (Yuzuru)",
"[APOLLO (JIRO)",
"[archea (Sasagawa Nagaru)",
"[Article 60 of Criminal Code (Shuhan)",
"[Ash wing (Makuro)",
"[ass (Itou Emiri)",
"[ASSAULTBEER (KOMA)",
"[Asterism (Shiyu)",
"[Asukara (Isao)",
"[Atamanurui MIX-eR",
"[Atonexia (Ato)",
"[AWAYOKUBA (Yukke)",
"[ayafujii private circle (Fujii Aya)",
"[Bamboo Ring! (Isobe)",
"[bb (Ume)",
"[Bear Tail (Chobi)",
"[BEVEL (Bebeyu)",
"[Biinyajou (Tomoi)",
"[Biyaku (Fujii Asaka)",
"[black line:01 (snail)",
"[Black Monkey",
"[BlackApple (Ryou)",
"[Blue Hawaii (Bu)",
"[BLUE HOOF (Wako)",
"[BOOBY TRAP (YANAGI)",
"[Bousou Cash-back (Himeki)",
"[C2.inc (C2)",
"[CACHE-CACHE (Nanjou Papiko)",
"[Calorie Off (Asahi)",
"[CASHLAIM (Haru)",
"[Celsius (Torikawa)",
"[Chaos Cradle",
"[Chemical Drop (Kirigaya Kari)",
"[CHERRY MOON (K-Zima)",
"[Chibineco Honpo (Chibineko Master)",
"[chicken (39rou)",
"[Chijoku An",
"[CHIN-UP (Pocchi)",
"[Chisha no Mi (Hidaka)",
"[choco-BANANA (Nanaki Nana)",
"[ChocoChro. (Gojoe)",
"[Chocolate Macaron (Yoshizawa Vanilla)",
"[Chojin/KAMONEGI",
"[ciao,baby (Miike)",
"[CLASSIC MILK, PEACE and ALIEN",
"[CLAZYSALT (Nazukichi)",
"[Club-Y",
"[CLUB-Z (Hinata Yagaki)",
"[COLOR PALETTE (Shiho)",
"[COMPLETE ZERO (Komino)",
"[COSMIQ (Nonoyama Chiuta)",
"[Crazy Joker (Kawase Hizuri)",
"[Crazy9 (Ichitaka)",
"[CRAZYPIG777 (Tonkatsu)",
"[cullet (Rou)",
"[D-2 (Miyasugi Miyu)",
"[D-Amb (Chitose Piyoko)",
"[dalia (Kadarinka)",
"[Dangan Orchestra (Shizumiya Hiiragi",
"[Dark Water (Tatsuse)",
"[delica (Mito)",
"[Denten, FUMUx2 (Tono)",
"[dg (Doguu)",
"[DIANA (Assa)",
"[DIETHELM (Mizuyuki)",
"[Dilcissime (Sakonishi)",
"[DMB (Kanda)",
"[Dobon (MiN)",
"[Dolce Einsatz (Tomoe Kiko)",
"[Dorobou Neko (NORIKO)",
"[Doronko Yuuyake",
"[Double Knockout (Natsuno)",
"[Double Slash (Orishima Yupopo)",
"[Doumo Sumimasen. (Dogeza)",
"[Douraku Kikou (Gan Son)",
"[downbeat (Kirimoto Yuuji)",
"[Draw Two (Draw2)",
"[Dreamy Kikaku",
"[Drum-kan (Kine)",
"[DSSK (Yorihito)",
"[DUMMY.N (Nemusugi Ruko)",
"[Earthly Southern Cross (Hashiba Rin)",
"[Ebony Thunder (EGAMI)",
"[ECHO (Echo Jiro)",
"[EgoRhythm (Sakiko)",
"[Enokinoki (Fujinami)",
"[Erectlip",
"[ErotIs (Narita Kou)",
"[Esebateira (Shibuki)",
"[esmeralda (Mitsuki)",
"[EX35 (Kamaboko RED)",
"[ez goin' (ez)",
"[FISH AND CHICKEN (Samoko)",
"[FLAT (Fujino Akitsugu)",
"[Folgore, Tommy (Gantai Higemania, Tomita)",
"[fudianshi",
"[Fukagawa (Kaya Tsuzurao)",
"[Fukagawa (Tsuzurao Kaya)",
"[Funyamafu (Sakazuki Ran)",
"[Gakuen Tengoku (Himi Kazusa)",
"[Gal Prince",
"[Gatekeeper (Sasaki Kisara)",
"[Genkaiten (URin)",
"[Gesuidou Megane (Jiro)",
"[Getsumen-Spiral (Mayama Satori)",
"[GiftKuchen (Shitori)",
"[GiGiGi Myou (Hayami Kuro)",
"[Gindama Explorer (Hinode Apartment.)",
"[Giselle, Honetukiniku (Rinkoyo, Sebone)",
"[Goma Saba (Natsuo Monaka)",
"[GOOD ANIMALS (Inukai)",
"[Gorilion (Kyuun)",
"[Gotou Sekai (Gotou Isa)",
"[ground-k (Kaneda)",
"[gulp (Hinotora)",
"[Gum Tape Type (Nauchi)",
"[GUZ (Okami Hazuki)",
"[HAIMITAI (Supana)",
"[Hakuchuu Doudou (Rian)",
"[Hanrangen ",
"[Hanrangen",
"[Hariko no Tora (Midoh Torako)",
"[Haru ga no (Harugano Kaoru)",
"[Harugane Colse (Inose)",
"[Hata Natsumi",
"[Hebereke (Nomiya Keyo)",
"[heinel (Mariko)",
"[Heppoko Drill (Soguni Mana)",
"[Higashi Mikuni Kamen (Saitoh Maho)",
"[HINATUYA (Ayanoumi)",
"[hn (Pirori)",
"[Hokou Kikai",
"[HONEY QP (Inochi Wazuka)",
"[Hoshimura (Tsugu Yuu)",
"[Hot Inari (Nari)",
"[HOT LIMIT (Shitsuki Aya)",
"[Houkiboshi (Maruna)",
"[HP0.01 (Eikichi)",
"[HPSK (SK)",
"[Hyouhon Shounen (Momo Sango)",
"[Ibaramichiotokogumi (myu, Natsuki)",
"[ick. (Karo)",
"[ima,mottomo. (Imamoto)",
"[InkStone (Amami Ryouko)",
"[Inomoto Rikako",
"[INSCRUTABLE (Kozuka Riho)",
"[Inugoya (Inu)",
"[Inuwanko",
"[Issou g (Ichinashi Kimi)",
"[Itachi Gokko (Takezamurai)",
"[J.O.C e.go!! (Midori Kouichi)",
"[J.O.C★e.go!! (Kasuga Souichi)",
"[Jam Session (Sudayoshi)",
"[Jamboree! (jin)",
"[Jamboree! (jin)",
"[Jomanda (Yamakuchi Suzuko, Minowa Eriko)",
"[K to S (RosaReah)",
"[K2★Crack (Hanaya Guy)",
"[Kaitei Heidan (Kura)",
"[KAKUNI (Iwano)",
"[KANGAROO KICK (Takagi Takumi)",
"[Kangaroo/TANSANSHONEN",
"[Karaage of the Year (Karaage Muchio)",
"[Karappo (1103)",
"[Karasu-dou (Aka Karasu)",
"[Karedake (2310)",
"[KCKC (Izumi Bouko)",
"[keenism (keeny)",
"[Keishin",
"[KH. (Yuki)",
"[Killer Bambi (Matsumoto Inaki)",
"[Killer Bambi (Matsumoto Inaki)",
"[kirari",
"[Kitsune (Tachikawa Negoro)",
"[KoDoMohonpo (Kayuge)",
"[KoDoMohonpo (Kayuge)",
"[Kokecocco (Karaage)",
"[Konekopunch (Hayakawa Minami)",
"[Koorigumo (KENN)",
"[koromo's factory (Koromo)",
"[Kouji (Yuuri)",
"[Koukai (Kobato)",
"[Koutetsuro (Sakiika.)",
"[krgmICE. (Kuromine)",
"[Kuromame Pack (Kuromame)",
"[Kuzumochi (Kuzukiri, Kuzuyu)",
"[Kyuukyuubako (Band Aid)",
"[La-Pis (Kuuya Wataru)",
"[LARZ-SILT AG+",
"[LARZ-SILT AG+",
"[laudanum (Hama Watari)",
"[laylow (Achi)",
"[LBK+, Romeo Plus (KEVIN, Ayame Chinami)",
"[LEFT (ore)",
"[LEGO! (Nakagawa)",
"[LI Project",
"[LioiL (Kawana Mario)",
"[LIQUID BERRY REVOLUTION (Ashita)",
"[Lotus (Asatsuki Hikaru)",
"[lozz (Konno Seara)",
"[LUFT SLOTT. (Aja.)",
"[M&LH (acca)",
"[MACARONICO (Macaroni, Nico)",
"[maguro. (Yukina)",
"[Majihama. (Mebata Shun)",
"[Makeinu (Hateru)",
"[Maraparte (Kojima Shoutarou)",
"[marigold (Momoe)",
"[Maririn",
"[Maru Tendon (Eikichi)",
"[Maru Tendon (Eikichi)",
"[Masamune Kokichi (Matsu Takeshi)",
"[Masamune Kokichi (Matsuzaki Tsukasa, Yamada Sansuke)",
"[Matango Honten (Tomakomai)",
"[MECCHORI (Mitsuru)",
"[Mekyaku Mayim (Matsumoto Ken)",
"[Mentaiko (Itto)",
"[Mercuro",
"[MERYx3 (Numeri)",
"[metro boy (Asino)",
"[MGN (Shimizu Aoto)",
"[MICAN-DOU (Matsumoto Mican)",
"[Mikli (Sugatamayo)",
"[Mine Noujou (Mine Mura)",
"[Minmin (Tomokasa)",
"[Mitsuya Yorgl (Futaba841)",
"[Mitsuzukitou (Matsuri)",
"[MixTurE (Nori)",
"[Mnemosyne (Ayakita)",
"[mocomoco (JOY)",
"[Moegun (Daikichi, Hachiya)",
"[Mokkuafunfun (Umai Sake)",
"[Momozakura (Momozakura Uduki)",
"[Monaco Meister (Kodama Naoko)",
"[Moudou (Kiritan)",
"[Mousou Katharsis (Asagi Shion)",
"[Mousou Wakusei (Moritake)",
"[MTD (Rei)",
"[MYBABY-10th (Fujiwara Ena)",
"[Nabe (Yoshitaka)",
"[Naikai (Emilio)",
"[Nanashi Shounen (7c)",
"[NANASHINO (mura.)",
"[Natsutama (Daichi Kouta)",
"[Natsutama]",
"[NATURAL DISTANCE (Anita)",
"[Ne2t (Neko do)",
"[NEO GENESIS (Sakaki Aruko)",
"[NEO-de (Natsuzaka)",
"[Neru Neru (Nerune)",
"[Netanian (Netani)",
"[neutral. (Shimajima Othello)",
"[Neyukidou (Takaku Nozomu)",
"[NG (Noda Gaku)",
"[Niboshiya (Mayokiti)",
"[Nn (Noni)",
"[NO RESET CLUB (Sakurai Shushushu)",
"[noff (Fly)",
"[NOIR (Michael)",
"[Nonomiya Chiyoko",
"[Nostalgia (Otsuki)",
"[Ns:plus (Isa)",
"[Nyanbers (Bingo)",
"[obake (Sakuma)",
"[oden.jpg (Mojyako)",
"[Ohige (Kanu)",
"[Ohige",
"[OJmomo (yoshi)",
"[OKAMU-LAND (Hobi)",
"[ONEM (Uto)",
"[oniyuri (Tayoko)",
"[Onjire (Tamy)",
"[Oomi Tsutou (Tokugawa Ranko, Hayami Masumi)",
"[Ooshiba Tetsuo",
"[Orange Peel (Misaragi)",
"[Origotoh, Yoidukiya (Suehiro Yoshiyuki, Touya)",
"[Oshiai Heshiai Dotukiai (smaru)",
"[Otomezaryuseigun (Mika)",
"[Ozo",
"[Palin (Hirano)",
"[palindrome (Mawari Ayako)",
"[Panda 4gou (Shima Kyousuke)",
"[pantwo (ziz)",
"[Param (Kyuuma)",
"[Pararira (Okayu)",
"[ParisPink (Parispi)",
"[Penguin Frontier",
"[PEPERMOON (Soraumi Riku)",
"[PERROs (Kai Hayato, Keita)",
"[PERROs",
"[pg (Toufu)",
"[Pink Elephant (Kotori)",
"[PINK GARDEN (Ashika Nozomu)",
"[Pinke (Kaya)",
"[plus810 (Yamada Non)",
"[pobee (Gurasuke)",
"[Pochon (Yosa, Chisato)",
"[Poison Carrot!!",
"[POM (Shishamo)",
"[Pomatobatake (Kin29 Nitaro)",
"[pp.mu! (Takepon)",
"[PROMENADE (Shibao Kenta)",
"[Pupu (Poron)",
"[Purin no Kanzume (IHANA Usagi)",
"[Qcumber (久理)",
"[QQaid (Kuro)",
"[Quartierlatin (Wasi)",
"[R*kaffy (Aichi Shiho)",
"[R2 (Sarry)",
"[Radistar (157)",
"[Raku saba shironeko (FENN)",
"[RB (Heso Kugi)",
"[RE:GA (Suzuki Ichifuyu)",
"[Rebellion (Janne Koheiji)",
"[Red Rose Party (Sumio)",
"[Renbu EXE (Subuta)",
"[Replicailia (Una)",
"[RIRIADOLL (Takewakamaru)",
"[RMB! (Yukichi)",
"[Rokka (Yuinoz)",
"[ROKUJO DAYS (Yoshidaya Roku)",
"[Rozaria (Azuna Yuzuki)",
"[RRO (Ruratto)",
"[RRO (Ruratto, Iko)",
"[Runa (Byakuan)",
"[Ruu Kikaku (Ruuen Rouga)",
"[Rycanthropy (Mizuki Gai)",
"[Rycanthropy (Mizuki Gai)",
"[Ryuusei Potechi (Hinami)",
"[SAIKARE (107 Shiki)",
"[Sakananohone (maza-)",
"[Sakananohone (maza-)",
"[Salt Peter (Tenma)",
"[Saragi (R5)",
"[SAWRED",
"[SECIAMU (Sakimoto)",
"[secret soldier (Yasuda Shinogu)",
"[Seishinteki Ni Koujoushin Ga Nai Mono Wa Baka da (Tomako)",
"[Seki Sabato (Tsukuru)",
"[Sengoku cartoon (Matsuzono)",
"[Shishunki Fortune (Taira Hitoshi)",
"[Shounen Byoukan (Kanno Izuka)",
"[Shounen Zoom (Shigeru)",
"[Shounen Zoom (Shigeru)",
"[Shuryousha (Urame)",
"[Shuukyuu Itsukasei (Touya Tsuduru)",
"[SILLKY BLANC (Otousan)",
"[SKYJACK (Kitajima)",
"[SM Potato (Kumo)",
"[Spira Mirabilis (Yamada Mitsubachi)",
"[SPNN (Nanashi, Supa)",
"[Strawberry55 (Mitsuya)",
"[STUDIO ASUMA (Matsumoto Seama)",
"[Studio Dimple (Tsumugi Kyuuta)",
"[SU (Enuko)",
"[sukinaco (Imai)",
"[super-hiropon (Ponta)",
"[Sushipuri (Kanbe Chuji)",
"[Swallow Sky (Rihara)",
"[T-CUBE+ (Nagiisora)",
"[Tagame Gengoroh",
"[Takaku Nozomu",
"[Takenoko Gohan VF (Takenokoya, Turn K)",
"[Takenoko Gohan, Buaifamu (Takenokoya)",
"[Takezamurai",
"[Tamago no Kara",
"[Tanakana_Kuchidakebanchou",
"[Tasomorera (Izumi Makoto)",
"[Taurin 1 Oku (Tataru)",
"[Tengai Aku Juumonji",
"[TETSU-SABI (Fumidzuki-ji A)",
"[The Powerfull Battery (BomBom)",
"[TK (Gohan)",
"[Tokage Ball (Ichikura Tokage)",
"[Tokyo Coin Rocker Baby (agaccho)",
"[Tokyo Note, UOHSAOH (Amamiya Amako)",
"[Tokyo Note, UOHSAOH (Amamiya Amako, Miwa Chikara)",
"[TomCat (Keita)",
"[Torajima-shi Kouhouka (Torajimaneko)",
"[TOTO (Satou Sugama)",
"[Tsunamushi",
"[Tukunent (Tukune Tissue)",
"[tunasand (Tuna)",
"[U.D.D",
"[UC*Parade (Satsuki)",
"[udon2soba (Tenpura Tamao)",
"[Ultimate Drug D-side",
"[UltimatePowers (RURU)",
"[UMBRELLA (Kasa)",
"[Underground Campaign",
"[UNVER (Shiroshita Ayu)",
"[Urusai Kokuen (Ekataraf)",
"[Usamimi Syndrome (Erutasuku)",
"[VAPOR (NEEMA)",
"[Vivace (Mikado)",
"[Voyager Project (Konoe Ayahisa)",
"[Waradoko (Warabi Ginta)",
"[Wasukoro (Nukobao)",
"[Wasukoro (Sakaki)",
"[WILD HALF (Ryo Takahashi)",
"[WORLD BOX (yuu)",
"[Wosaru Shoukoukai (Nekotsuki Izumi, Heesuke)",
"[Wyinji",
"[Yabure Kabure (Agemon)",
"[Yakisaketeishoku (Xigma)",
"[Yakou Kyoku (Ihama Daka)",
"[YAMY (Mukko)",
"[Yaranaika (NakamuraQ)",
"[yemak (yemak)",
"[Yes,sir. (Epuko)",
"[Yinghua (sinba)",
"[Yotto. (Yoro, Tomozou)",
"[Yu-cho (Pal)",
"[Yutsuki (Ryuuk)",
"[Yuzuru / LEVIN",
"[Z32 (Z32)",
"[Zanmai (Yuni)",
"[Zanmai (Yunisuke)",
"[Zarigani ARMS (20)",
"[zatta (tomose)",
"[Zenkai Charge RL (Mio, Kusuhara Nao)",
"[アベハル",
"[田亀源五郎",  
"[魚肉と鳥肉",
  ];

  homos = homos.map(function(e){return e.toLowerCase()});
  
  function isHomo(text){
    text = text.toLowerCase()
    for(ii = 0; ii < homos.length; ii++){
      if(text.indexOf(homos[ii]) > -1){
        return homos[ii];
      }
    }
    return false;
  }

  var getURL = chrome.extension.getURL;
  var prevRandomNum = 0;
  $("div.id2 a").each(function(){
    try{
      var text = this.text;
      if(text){
          var block = isHomo(text);
          if(block){
            // debugger;
            var id3Div = $(this.parentNode.parentNode).children(".id3");
            var gayPic = id3Div.children("a").children("img");
            gayPic = $(gayPic);

            //js Math.random is not random enough
            var randomNum = Math.floor(Math.random() * 5);
            randomNum = randomNum === prevRandomNum?　Math.floor(Math.random() * 5) : randomNum;
            prevRandomNum = randomNum;

            gayPic.attr("src", getURL("rurutie-" + randomNum + ".jpg")||
                                  getURL("rurutie.jpg") ||"");
            gayPic.attr("alt", "");
            gayPic.attr("blocked_because", block);
          }
      }
    }catch(e){
    }
  })

})();















