(function(){

  var homos = [
    //--------------parody-----------------
    //"(One-Punch Man)", //tatsumaki is cute. Why you choose this, fujosi!
"(Haikyuu!!)",
"(Shingeki no Kyojin)",  //Mikasa is not cute anyway
"(Kuroko no Basuke)", 
"(Katekyoo Hitman REBORN!)",
"(Touken Ranbu)",
"(Yowamushi Pedal)",
"(Uta no Prince-sama)",
"(Hoozuki no Reitetsu)",
"(Kekkai Sensen)",
"(Free!)",
"(ALDNOAH.ZERO)",
"(Ensemble Stars!)",
"(Sengoku Basara)",
"(Bakumatsu Rock)",
"(DRAMAtical Murder)",
"(Ao no Exorcist)",
"(Daiya no Ace)",
"(Gintama)",
"(Katekyo Hitman REBORN!)",
"リヴァイ兵長",  //I hate this short guy!!
"少年×ケモノ",   
"ケモホモ",
"(Teenage Mutant Ninja Turtles)",
"(Buraiden Gai)",
"(Prince of Tennis)",
"(TIGER & BUNNY)",
"(Osomatsu-san)",
"(GANGSTA.)",
"(Toriko)",
"(Durarara!!)",
"(Inazuma Eleven)",
"(Summer Wars)", //why on earth they choose!!
"(Tokyo Ghoul)", 
"(Kaiji)", //OMG
"(Dramatical Murder)",
//------------author---------------
"[[Natsutama (Daichi Kouta)",
"[Akiya (Suzusawa Aki)",
"[Taurin 1 Oku (Tataru)",
"[archea (Sasagawa Nagaru)",
"[KoDoMohonpo (Kayuge)",
"[pobee (Gurasuke)",
"[DIANA (Assa)",
"[GOOD ANIMALS (Inukai)",
"[LEFT (ore)",
"[Enokinoki (Fujinami)",
"[COLOR PALETTE (Shiho)",
"[KoDoMohonpo (Kayuge)",
"[pobee (Gurasuke)",
"[Hot Inari (Nari)",
"[Houkiboshi (Maruna)",
"[plus810 (Yamada Non)",
"[Akitaku Kikaku (Taku Hiraku)",
"[BLUE HOOF (Wako)",
"[bb (Ume)",
"[Shuryousha (Urame)",
"[dg (Doguu)",
"[Strawberry55 (Mitsuya)",
"[Runa (Byakuan)",
"[Tasomorera (Izumi Makoto)",
"[Nabe (Yoshitaka)",
"[Shuukyuu Itsukasei (Touya Tsuduru)",
"[krgmICE. (Kuromine)",
"[Hebereke (Nomiya Keyo)",
"[Dobon (MiN)",
"[Dorobou Neko (NORIKO)",
"[Palin (Hirano)",
"[KAKUNI (Iwano)",
"[Gorilion (Kyuun)",
"[secret soldier (Yasuda Shinogu)",
"[Esebateira (Shibuki)",
"[Takezamurai",
"[Underground Campaign",
"[Akuochisukii Kyoushitsu (Akuochisukii Sensei)",
"[Poison Carrot!!",
"[田亀源五郎",  
"[PERROs (Kai Hayato, Keita)",
"[PERROs",
"[Itachi Gokko (Takezamurai)",
"[Jamboree! (jin)",
"[Aozora (Nosada)",
"[Yakisaketeishoku (Xigma)",
"[Pochon (Yosa, Chisato)",
"[Bear Tail (Chobi)",
"[Radistar (157)",
"[Fukagawa (Tsuzurao Kaya)",
"[Yakou Kyoku (Ihama Daka)",
"[Draw Two (Draw2)",
"[Ooshiba Tetsuo",
"[La-Pis (Kuuya Wataru)",
"[[Natsutama]",
"[Neyukidou (Takaku Nozomu)",
"[Takaku Nozomu",
"[Ryuusei Potechi (Hinami)",
"[The Powerfull Battery (BomBom)",
"[Mousou Wakusei (Moritake)",
"[ECHO (Echo Jiro)",
"[Masamune Kokichi (Matsu Takeshi)",
"[Doronko Yuuyake",
"[Maru Tendon (Eikichi)",
"[NOIR (Michael)",
"[[8°]",
"[[魚肉と鳥肉",
"[GiftKuchen (Shitori)",
"[Dangan Orchestra (Shizumiya Hiiragi",
"[Ambient (Kuriyama Natsuki)",
"[Killer Bambi (Matsumoto Inaki)",
"[InkStone (Amami Ryouko)",

"[001 (Iimo)",
"[10.10MHz (Totofumi)",
"[4DIP (Tarte)",
"[84 (Hashi)",
"[8days (Kuon Marino)",
"[A-mw. (makka)",
"[Akareshina (Hidaka Naruse)",
"[Asukara (Isao)",
"[Atonexia (Ato)",
"[AWAYOKUBA (Yukke)",
"[Blue Hawaii (Bu)",
"[Celsius (Torikawa)",
"[chicken (39rou)",
"[CHIN-UP (Pocchi)",
"[COMPLETE ZERO (Komino)",
"[CRAZYPIG777 (Tonkatsu)",
"[Drum-kan (Kine)",
"[DSSK (Yorihito)",
"[EX35 (Kamaboko RED)",
"[FISH AND CHICKEN (Samoko)",
"[Getsumen-Spiral (Mayama Satori)",
"[Goma Saba (Natsuo Monaka)",
"[Gum Tape Type (Nauchi)",
"[INSCRUTABLE (Kozuka Riho)",
"[K to S (RosaReah)",
"[LEGO! (Nakagawa)",
"[Matango Honten (Tomakomai)",
"[Moudou (Kiritan)",
"[Mousou Katharsis (Asagi Shion)",
"[NEO GENESIS (Sakaki Aruko)",
"[neutral. (Shimajima Othello)",
"[obake (Sakuma)",
"[ONEM (Uto)",
"[pg (Toufu)",
"[Pink Elephant (Kotori)",
"[Poison Carrot!!",
"[RRO (Ruratto)",
"[SECIAMU (Sakimoto)",
"[Tokyo Note, UOHSAOH (Amamiya Amako)",
"[tunasand (Tuna)",
"[Urusai Kokuen (Ekataraf)",
"[VAPOR (NEEMA)",
"[Yabure Kabure (Agemon)",
"[Yaranaika (NakamuraQ)",
"[yemak (yemak)",
"[Yutsuki (Ryuuk)",
"[Z32 (Z32)",
"[Hata Natsumi",

"[100Mjack (Ebisawa Nira)",
"[238 (Hachi, Mitsu)",
"[23924 (Miko)",
"[39dmp (tachibanaei)",
"[3×3CROSS (Marimo)",
"[6109 (Kirishiki Tokico)",
"[6counter (Shuukichi)",
"[:DOG VILLE, Tokyo Coin Rocker Baby (agaccho, Mitsumura)",
"[@N (unico)",
"[ADVANX (ADVANX)",
"[Afuroyaen (Nyankichi)",
"[Akareshina (Hidaka Naruse)",
"[Akiya (Suzusawa Aki)",
"[Akuochisukii Kyoushitsu (Akuochisukii Sensei)",
"[Altopia (Alto)",
"[Amarans (Fujimura Marina)",
"[Amarans, caplet0.5 (Fujimura Marina, mego)",
"[ame-kan (K.Hinagi)",
"[anything (naop)",
"[Aozora (Nosada)",
"[Apoepo Company. (Yuzuru)",
"[APOLLO (JIRO)",
"[Article 60 of Criminal Code (Shuhan)",
"[Ash wing (Makuro)",
"[ass (Itou Emiri)",
"[ASSAULTBEER (KOMA)",
"[Asterism (Shiyu)",
"[Atamanurui MIX-eR",
"[ayafujii private circle (Fujii Aya)",
"[BEVEL (Bebeyu)",
"[Biinyajou (Tomoi)",
"[Biyaku (Fujii Asaka)",
"[black line:01 (snail)",
"[BlackApple (Ryou)",
"[BOOBY TRAP (YANAGI)",
"[Bousou Cash-back (Himeki)",
"[C2.inc (C2)",
"[CACHE-CACHE (Nanjou Papiko)",
"[Calorie Off (Asahi)",
"[CG",
"[Chemical Drop (Kirigaya Kari)",
"[CHERRY MOON (K-Zima)",
"[Chisha no Mi (Hidaka)",
"[choco-BANANA (Nanaki Nana)",
"[ChocoChro. (Gojoe)",
"[Chocolate Macaron (Yoshizawa Vanilla)",
"[Chojin/KAMONEGI & Kangaroo/TANSANSHONEN",
"[CLASSIC MILK, PEACE and ALIEN (Asaoka Natsuki, Tonase Fuki)",
"[CLAZYSALT (Nazukichi)",
"[Club-Y",
"[CLUB-Z (Hinata Yagaki)",
"[COSMIQ (Nonoyama Chiuta)",
"[Crazy9 (Ichitaka)",
"[cullet (Rou)",
"[D-2 (Miyasugi Miyu)",
"[D-Amb (Chitose Piyoko)",
"[dalia (Kadarinka)",
"[Dan",
"[delica (Mito)",
"[Denten, FUMUx2 (Tono)",
"[DIETHELM (Mizuyuki)",
"[Digital",
"[Dilcissime (Sakonishi)",
"[DMB (Kanda)",
"[Dolce Einsatz (Tomoe Kiko)",
"[Double Slash (Orishima Yupopo)",
"[downbeat (Kirimoto Yuuji)",
"[Dreamy Kikaku",
"[DUMMY.N (Nemusugi Ruko)",
"[Earthly Southern Cross (Hashiba Rin)",
"[Ebony Thunder (EGAMI)",
"[EgoRhythm (Sakiko)",
"[Erectlip",
"[ErotIs (Narita Kou)",
"[Esebateira (Shibuki)",
"[esmeralda (Mitsuki)",
"[EX35 (Kamaboko RED)",
"[ez goin' (ez)",
"[FLAT (Fujino Akitsugu)",
"[Folgore, Tommy (Gantai Higemania, Tomita)",
"[fudianshi",
"[Fukagawa (Kaya Tsuzurao)",
"[Fukagawa (Tsuzurao Kaya)",
"[Funyamafu (Sakazuki Ran)",
"[Gakuen Tengoku (Himi Kazusa)",
"[Gatekeeper (Sasaki Kisara)",
"[Genkaiten (URin)",
"[Gesuidou Megane (Jiro)",
"[Giselle, Honetukiniku (Rinkoyo, Sebone)",
"[Gotou Sekai (Gotou Isa)",
"[ground-k (Kaneda)",
"[gulp (Hinotora)",
"[GUZ (Okami Hazuki)",
"[HAIMITAI (Supana)",
"[Hakuchuu Doudou (Rian)",
"[Hanrangen (Various)",
"[Hariko no Tora (Midoh Torako)",
"[heinel (Mariko)",
"[Heppoko Drill (Soguni Mana)",
"[Higashi Mikuni Kamen (Saitoh Maho)",
"[HINATUYA (Ayanoumi)",
"[hn (Pirori)",
"[Hokou Kikai",
"[Hoshimura (Tsugu Yuu)",
"[HOT LIMIT (Shitsuki Aya)",
"[HP0.01 (Eikichi)",
"[HPSK (SK)",
"[Hyouhon Shounen (Momo Sango)",
"[Ibaramichiotokogumi (myu, Natsuki)",
"[ima,mottomo. (Imamoto)",
"[Incomplete",
"[Inugoya (Inu)",
"[Inuwanko",
"[Issou g (Ichinashi Kimi)",
"[J.O.C e.go!! (Midori Kouichi)",
"[Jam Session (Sudayoshi)",
"[Jamboree! (jin)",
"[Jomanda (Yamakuchi Suzuko, Minowa Eriko)",
"[K2★Crack (Hanaya Guy)",
"[Kaitei Heidan (Kura)",
"[KANGAROO KICK (Takagi Takumi)",
"[Karappo (1103)",
"[Karasu-dou (Aka Karasu)",
"[KCKC (Izumi Bouko)",
"[keenism (keeny)",
"[Keishin",
"[KH. (Yuki)",
"[kirari",
"[Kitsune (Tachikawa Negoro)",
"[Kokecocco (Karaage)",
"[Koukai (Kobato)",
"[Koutetsuro (Sakiika.)",
"[Kuzumochi (Kuzukiri, Kuzuyu)",
"[Kyuukyuubako (Band Aid)",
"[LARZ-SILT AG+",
"[LBK+, Romeo Plus (KEVIN, Ayame Chinami)",
"[LioiL (Kawana Mario)",
"[LIQUID BERRY REVOLUTION (Ashita)",
"[Lotus (Asatsuki Hikaru)",
"[LUFT SLOTT. (Aja.)",
"[MACARONICO (Macaroni, Nico)",
"[maguro. (Yukina)",
"[Makeinu (Hateru)",
"[Maraparte (Kojima Shoutarou)",
"[marigold (Momoe)",
"[Maririn",
"[MECCHORI (Mitsuru)",
"[Mekyaku Mayim (Matsumoto Ken)",
"[MERYx3 (Numeri)",
"[MGN (Shimizu Aoto)",
"[MICAN-DOU (Matsumoto Mican)",
"[Mikli (Sugatamayo)",
"[Minmin (Tomokasa)",
"[Mitsuzukitou (Matsuri)",
"[MixTurE (Nori)",
"[Mnemosyne (Ayakita)",
"[mocomoco (JOY)",
"[Moegun (Daikichi, Hachiya)",
"[Mokkuafunfun (Umai Sake)",
"[Momozakura (Momozakura Uduki)",
"[Monaco Meister (Kodama Naoko)",
"[Moudou (Kiritan)",
"[Naikai (Emilio)",
"[Nanashi Shounen (7c)",
"[NANASHINO (mura.)",
"[NEO GENESIS (Sakaki Aruko)",
"[NEO-de (Natsuzaka)",
"[Neru Neru (Nerune)",
"[Netanian (Netani)",
"[NG (Noda Gaku)",
"[NO RESET CLUB (Sakurai Shushushu)",
"[noff (Fly)",
"[Nonomiya Chiyoko",
"[Nostalgia (Otsuki)",
"[Ns:plus (Isa)",
"[Nyanbers (Bingo)",
"[oden.jpg (Mojyako)",
"[Ohige",
"[OJmomo (yoshi)",
"[oniyuri (Tayoko)",
"[Onjire (Tamy)",
"[Oomi Tsutou (Tokugawa Ranko, Hayami Masumi)",
"[Orange Peel (Misaragi)",
"[Origotoh, Yoidukiya (Suehiro Yoshiyuki, Touya)",
"[Oshiai Heshiai Dotukiai (smaru)",
"[Otomezaryuseigun (Mika)",
"[Ozo",
"[palindrome (Mawari Ayako)",
"[Panda 4gou (Shima Kyousuke)",
"[pantwo (ziz)",
"[Param (Kyuuma)",
"[Pararira (Okayu)",
"[ParisPink (Parispi)",
"[PEPERMOON (Soraumi Riku)",
"[PERROs (Kai Hayato, Keita)",
"[PINK GARDEN (Ashika Nozomu)",
"[Pinke (Kaya)",
"[PROMENADE (Shibao Kenta)",
"[Pupu (Poron)",
"[Purin no Kanzume (IHANA Usagi)",
"[Qcumber (久理)",
"[QQaid (Kuro)",
"[R2 (Sarry)",
"[Radistar (157)",
"[Raku saba shironeko (FENN)",
"[RE:GA (Suzuki Ichifuyu)",
"[Rebellion (Janne Koheiji)",
"[Red Rose Party (Sumio)",
"[Renbu EXE (Subuta)",
"[RIRIADOLL (Takewakamaru)",
"[RMB! (Yukichi)",
"[Rokka (Yuinoz)",
"[Rycanthropy (Mizuki Gai)",
"[Ryuusei Potechi (Various)",
"[S G",
"[SAIKARE (107 Shiki)",
"[Sakananohone (maza-)",
"[Salt Peter (Tenma)",
"[SECIAMU (Sakimoto)",
"[Seishinteki Ni Koujoushin Ga Nai Mono Wa Baka da (Tomako)",
"[Seki Sabato (Tsukuru)",
"[Sengoku cartoon (Matsuzono)",
"[Shishunki Fortune (Taira Hitoshi)",
"[Shounen Byoukan (Kanno Izuka)",
"[Shounen Zoom (Shigeru)",
"[Shuukyuu Itsukasei (Touya Tsuduru)",
"[SKYJACK (Kitajima)",
"[Spira Mirabilis (Yamada Mitsubachi)",
"[SPNN (Nanashi, Supa)",
"[STUDIO ASUMA (Matsumoto Seama)",
"[SU (Enuko)",
"[super-hiropon (Ponta)",
"[Sushipuri (Kanbe Chuji)",
"[Swallow Sky (Rihara)",
"[T-CUBE+ (Nagiisora)",
"[Tagame Gengoroh",
"[Takenoko Gohan VF (Takenokoya, Turn K)",
"[Takezamurai",
"[Tamago no Kara",
"[Tanakana_Kuchidakebanchou",
"[TETSU-SABI (Fumidzuki-ji A)",
"[Tokage Ball (Ichikura Tokage)",
"[Tokyo Coin Rocker Baby (agaccho)",
"[TomCat (Keita)",
"[Tukunent (Tukune Tissue)",
"[tunasand (Tuna)",
"[U.D.D",
"[UC*Parade (Satsuki)",
"[Ultimate Drug D-side",
"[UltimatePowers (RURU)",
"[UMBRELLA (Kasa)",
"[UNVER (Shiroshita Ayu)",
"[VAPOR (NEEMA)",
"[Vivace (Mikado)",
"[Voyager Project (Konoe Ayahisa)",
"[Waradoko (Warabi Ginta)",
"[Wasukoro (Sakaki)",
"[WILD HALF (Ryo Takahashi)",
"[WORLD BOX (yuu)",
"[Wosaru Shoukoukai (Nekotsuki Izumi, Heesuke)",
"[Yakou Kyoku (Ihama Daka)",
"[Yinghua (sinba)",
"[Yu-cho (Pal)",
"[Yuzuru / LEVIN",
"[Zanmai (Yuni)",
"[Zanmai (Yunisuke)",
"[Zenkai Charge RL (Mio, Kusuhara Nao)",
"[アベハル",
  ];

  homos = homos.map(function(e){return e.toLowerCase()});
  
  function isHomo(text){
    text = text.toLowerCase()
    for(ii = 0; ii < homos.length; ii++){
      if(text.indexOf(homos[ii]) > -1){
        return true;
      }
    }
    return false;
  }
  
  $("div.id2 a").each(function(){
    try{
      var text = this.text;
      if(text && isHomo(text)){
          // debugger;
          var id3Div = $(this.parentNode.parentNode).children(".id3");
          var gayPic = id3Div.children("a").children("img");
          gayPic = $(gayPic);
          gayPic.attr("src", chrome.extension.getURL("rurutie.jpg")||"");
          gayPic.attr("alt", "")
      }
    }catch(e){
    }


  })

})();















